<a href="https://colab.research.google.com/github/Hashhhhhhhh/ML-with-Python/blob/main/Calculating_network_error_with_loss_Cross_Entropy_Loss.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
softmax_outputs = np.array([[0.7, 0.1, 0.2],
 [0.1, 0.5, 0.4],
 [0.02, 0.9, 0.08]])
class_targets = [0, 1, 1]
print(softmax_outputs[[0, 1, 2], class_targets])

[0.7 0.5 0.9]


In [2]:
range(len(softmax_outputs))

range(0, 3)

In [4]:
print(-np.log(softmax_outputs[
 range(len(softmax_outputs)), class_targets
]))
neg_log = -np.log(softmax_outputs[
 range(len(softmax_outputs)), class_targets
 ])
average_loss = np.mean(neg_log)
print(average_loss)

[0.35667494 0.69314718 0.10536052]
0.38506088005216804


If the data is one hot encoded!!

One-Hot encoding converts categorical data into binary data. For example, A feature fruit with values : apple, mango,orange. After encoding:


In [7]:
import numpy as np

matrix = np.array([[1, 0,0], [0, 1, 0],[0,0,1]])

print(matrix)


[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [5]:
y_true_check = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 1, 0]
])
y_pred_clipped_check = np.array([
    [0.7, 0.2, 0.1],
    [0.1, 0.5, 0.4],
    [0.02, 0.9, 0.08]
])
A = y_true_check*y_pred_clipped_check
B = np.sum(A, axis = 1)
C = - np.log(B)
print(C)
print(np.mean(C))

[0.35667494 0.69314718 0.10536052]
0.38506088005216804
